version: "3.9"

services:
    nginx:
        container_name: nginx
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./docker/nginx/hosts:/etc/nginx/conf.d
        links:
            - apache2
        depends_on:
            -  apache2

    apache2:
        container_name: apache2
        build:
            context: .
            dockerfile: docker/apache2/DockerFile
        volumes:
            - ./:/var/www
        environment:
            XDEBUG_CONFIG: remote_host=host.docker.internal
            PHP_IDE_CONFIG: serverName=localhost

    percona:
        container_name: percona
        image: percona
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: laravel

    rabbitmq:
        image: rabbitmq:latest
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - rabbitmq:/var/lib/rabbitmq
            - rabbitmq-logs:/var/log/rabbitmq

    redis:
        container_name: db-redis
        build:
            context: .
            dockerfile: docker/redis/Dockerfile
        sysctls:
            - net.core.somaxconn=1000
        ports:
            - 6379:6379
#        volumes:
#            - ./docker/redis/data:/var/lib/redis

#networks:
#    network:
#        driver: bridge

volumes:
    rabbitmq-logs:
    rabbitmq: