version: "3.9"

services:
    nginx:
        container_name: nginx
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./docker/nginx/hosts:/etc/nginx/conf.d
            - ./:/var/www
        links:
            - php

    php:
        container_name: php
        build:
            context: .
            dockerfile: ./docker/nginx/php/DockerFile
        volumes:
            - ./:/var/www
